name: attributes
description: Decode and encode structured data type-safely from JSON. Utilities for data objects, entities and values.
version: 0.8.1
repository: https://github.com/navibyte/dataflow
homepage: https://github.com/navibyte/dataflow/tree/main/dart/attributes

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  equatable: ^2.0.0
  intl: ^0.17.0
  meta: ^1.7.0

dev_dependencies:
  test: ^1.16.4
  very_good_analysis: ^2.4.0
