name: attributes
description: Decode and encode structured data type-safely from JSON. Utilities for data objects, entities and values.
version: 0.7.3
repository: https://github.com/navibyte/dataflow
homepage: https://github.com/navibyte/dataflow/tree/main/dart/attributes

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  equatable: ^2.0.0
  meta: ^1.3.0
  intl: ^0.17.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.4
