name: datatools
description: A library for Dart to help fetching data from HTTP and file resources and other data sources.
version: 0.7.0
repository: https://github.com/navibyte/dataflow
homepage: https://github.com/navibyte/dataflow/tree/main/dart/datatools

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  equatable: ^2.0.0
  meta: ^1.3.0
  http: ^0.13.0
  http_parser: ^4.0.0
  path: ^1.8.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.4
