name: datatools
description: A library for Dart to help fetching data from HTTP and file resources and other data sources.
version: 0.8.2
repository: https://github.com/navibyte/dataflow
homepage: https://github.com/navibyte/dataflow/tree/main/dart/datatools

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  equatable: ^2.0.0
  http: ^0.13.0
  http_parser: ^4.0.0
  meta: ^1.7.0
  path: ^1.8.0

dev_dependencies:
  test: ^1.16.4
  very_good_analysis: ^4.0.0
