name: datatools
description: A library for Dart to help fetching data from HTTP and file resources and other data sources.
version: 1.0.0
repository: https://github.com/navibyte/dataflow
homepage: https://github.com/navibyte/dataflow/tree/main/dart/datatools

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  equatable: ^2.0.0
  http: ^1.1.0
  http_parser: ^4.0.0
  meta: ^1.9.0
  path: ^1.8.0

dev_dependencies:
  test: ^1.24.0
  very_good_analysis: ^5.0.0
